{
    'name': 'Colette Library',
    'version': '14.0.1.0.0',
    'summary': 'Manage books easily',
    'description': 'Learn how to create an add-on moduleb',
    'live_test_url': 'https://colette.odooteam.helpbots.sg/',
    'category': 'Productivity',
    'author': 'Colette',
    'maintainer': 'Epikla',
    'company': 'Epikla',
    'website': 'https://colette.odooteam.helpbots.sg/',
    'depends': ['base', 'contacts'] ,       
    'data': [
        'views/library_book.xml',
        'views/library_book_category.xml',
        'views/library_book_rent.xml',
        'security/groups.xml',
        'security/ir.model.access.csv',
        'wizard/library_book_rent_wizard.xml',
        'wizard/library_book_return_wizard.xml',
        'data/library_stage.xml',
        'reports/book_rent_templates.xml',
        'reports/book_rent_report.xml',
        # 'views/library_book_statistics.xml',
        # 'views/res_config_settings_views.xml',
    ],
    'demo': [''],
    'images': ['static/icon.png'],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'AGPL-3',
}
